name: RpgEssentials
main: me.duckdoom5.RpgEssentials.RpgEssentials
version: 1.3.5
load: startup
depend: [Spout]
softdepend: [Vault]

commands:
  rpg:
    description: general rpg commands
    aliases: [RPG, roleplayinggame]
    usage: |
      /rpg [command]
  rnpc:
    description: general npc commands
    aliases: [RNPC]
    usage: |
      /rnpc [command]

permissions:
  rpgessentials.rpg.texturepack.playerschoise:
    description: Gives the player permission to choose there own texturepack
    default: op
    
  rpgessentials.rpg.cape:
    description: Gives access to rpg cape command
    default: true
    
  rpgessentials.rpg.accessory:
    description: Gives access to rpg cape command
    default: true
    
  rpgessentials.rpg.reload:
    description: Gives access to rpg reload command
    default: op
    
  rpgessentials.rpg.capeother:
    description: Gives access to rpg cape command
    default: op
    
  rpgessentials.rpg.feed:
    description: Gives access to rpg feed command
    default: op
    
  rpgessentials.rpg.feedother:
    description: Gives access to rpg feed command
    default: op
    
  rpgessentials.rpg.heal:
    description: Gives access to rpg heal command
    default: op
    
  rpgessentials.rpg.healother:
    description: Gives access to rpg heal command
    default: op
    
  rpgessentials.rpg.help:
    description: Gives access to rpg help command
    default: true
    
  rpgessentials.rpg.jump:
    description: Gives access to rpg jump command
    default: op
    
  rpgessentials.rpg.jumpother:
    description: Gives access to rpg jump command
    default: op
    
  rpgessentials.rpg.money.set:
    description: Gives access to rpg money command
    default: op
    
  rpgessentials.rpg.money.setother:
    description: Gives access to rpg money command
    default: op
    
  rpgessentials.rpg.skin:
    description: Gives access to rpg skin command
    default: true
    
  rpgessentials.rpg.skinother:
    description: Gives access to rpg skin command
    default: op
    
  rpgessentials.rpg.speed:
    description: Gives access to rpg speed command
    default: op
    
  rpgessentials.rpg.speedother:
    description: Gives access to rpg speed command
    default: op
    
  rpgessentials.rpg.time:
    description: Gives access to rpg time command
    default: true
    
  rpgessentials.rpg.timeset:
    description: Gives access to rpg time command
    default: op
    
  rpgessentials.rpg.titlehide:
    description: Gives access to rpg title command
    default: op
    
  rpgessentials.rpg.title:
    description: Gives access to rpg title command
    default: op
    
  rpgessentials.rpg.titleother:
    description: Gives access to rpg title command
    default: op
    
  rpgessentials.rpg.weather:
    description: Gives access to rpg weather command
    default: op
    
  rpgessentials.npc.admin:
    description: Gives access to npc admin command
    default: op
    
  rpgessentials.npc.armor:
    description: Gives access to npc armor command
    default: op
    
  rpgessentials.npc.cape:
    description: Gives access to npc cape command
    default: op
    
  rpgessentials.npc.create:
    description: Gives access to npc create command
    default: op
    
  rpgessentials.npc.item:
    description: Gives access to npc item command
    default: op
    
  rpgessentials.npc.move:
    description: Gives access to npc move command
    default: op
    
  rpgessentials.npc.owner:
    description: Gives access to npc owner command
    default: op
    
  rpgessentials.npc.remove:
    description: Gives access to npc remove command
    default: op
    
  rpgessentials.npc.rename:
    description: Gives access to npc rename command
    default: op
    
  rpgessentials.npc.select:
    description: Gives access to npc select command
    default: op
    
  rpgessentials.npc.skin:
    description: Gives access to npc skin command
    default: op
    
  rpgessentials.npc.text:
    description: Gives access to npc text command
    default: op
    
  rpgessentials.npc.type:
    description: Gives access to npc type command
    default: op